### ISSUE TITLE
Demo error

### ISSUE THREAD

**Issue by henry2004y** [JuliaDiffEq/DiffEqOperators.jl#161]
Hi,

I just found this package and was trying to run some simple demos. However, for the simple code I found on discourse below, it just returned error:
```
using DiffEqOperators

deriv = 2 # 2nd order derivative.
order = 2 # 2nd order approximation.
N  = 100  # Number of grid points.
xs = range(0,stop=2π,length=N)
dx = xs[2] - xs[1] 
#
# Use Delta to denote the Laplace operator.
#
Δ = DerivativeOperator{Float64}(deriv,order,dx,N,:Dirichlet0,:Dirichlet0)
```

> ERROR: MethodError: no method matching DerivativeOperator{Float64,N,Wind,T2,S1,S2,T3,F} where F where T3 where S2<:(StaticArrays.SArray{Tuple{S},T,1,S} where T where S) where S1 where T2 where Wind where N(::Int64, ::Int64, ::Float64, ::Int64, ::Symbol, ::Symbol)

The same issue happened with the demo code in [GSoC 2017: Efficient Discretizations of PDE Operators](https://julialang.org/blog/2017/09/gsoc-derivative_operators). 

I was trying with both Julia 1.1 and Julia 1.2

**Comment by ChrisRackauckas** [comment]
That syntax is not up to date. Please see the README. A lot has changed since the alpha version.

**Comment by henry2004y** [comment]
Is there an equivalent expression for the old DerivativeOperator where central difference is performed in the interior while one-sided difference is performed on the sides?

**Comment by ChrisRackauckas** [comment]
Yes, just DerivativeOperator with Neumann.
