### ISSUE TITLE
Interface for when the Jacobian is known analytically

### ISSUE THREAD

**Issue by rveltz** [JuliaDiffEq/DiffEqOperators.jl#176]
If I have a vector field `f!(du,u,p,t)` and its differential at `u` applied to `v` given by `df!(du,u,v,p,t)`. How can I use `DiffEqOperators` to pass the analytical jacobian? I know I can do
```
ff = ODEFunction(f!, jac_prototype = JacVecOperator{Float64}(f!,x0,p))
```
but I am interested in the case where I have an expression for the Jacobian.

It seems it should be a modification of the code for `JacVecOperator`. Is there any other way?

Thank you for your help,

**Comment by ChrisRackauckas** [comment]
You can use the MatrixFreeOperator: https://github.com/JuliaDiffEq/DiffEqOperators.jl/blob/master/src/matrixfree_operators.jl

**Comment by rveltz** [comment]
Sorry but I don't understand what you suggest. To me `MatrixFreeOperator` does not provide a way to say that the jacobian is evaluated at `u` on tangent vector `v`. 

> A MatrixFreeOperator is a linear operator A*u where the action of A is explicitly defined by an in-place function f(du, u, p, t).

The definition of my linear operator is `v->df!(du,u,v,p,t)` has more arguments than above.

**Comment by ChrisRackauckas** [comment]
In this setup, `update_coefficients!` would be used to update the values in `p` so that the operator becomes `J(u,p,t)`, and then it will perform `J(u,p,t)*v`. However, I can see how this is far less than ideal, so we should probably create an operator to simplify this a bit.

**Comment by rveltz** [comment]
You mean that I need to create a struct to record `u,p`? It seems that `JacVecOperator` has more or less this interface

**Comment by ChrisRackauckas** [comment]
Yeah, that's what `JacVecOperator` is doing. It just records the pointers and then uses it. So this just needs a similar wrapper, but without the AD part.

**Comment by rveltz** [comment]
it is pretty simple actually but one has to modify `JacVecOperator` to add `df` and parametrise the type of `autodiff` so that df is called when `typeof(autodiff) != Bool` using dispach for example. If this is done I could plug `ODEProblem` in [PseudoArcLengthContinuation.jl](https://github.com/rveltz/PseudoArcLengthContinuation.jl). I would need to extract the linearsolver though which does not seem incoded in `ODEProblem`
