### ISSUE TITLE
typo/bug in utils.jl

### ISSUE THREAD

**Issue by fhenneke** [JuliaDiffEq/DiffEqOperators.jl#199]
On the right hand side of
https://github.com/JuliaDiffEq/DiffEqOperators.jl/blob/a55b696ec6f4fe8b0307a2dcfec06665a382a7d2/src/utils.jl#L16
it should be `A` instead of `a`, right?

**Comment by ChrisRackauckas** [comment]
Yup, I guess a blind spot in the tests?

https://github.com/JuliaDiffEq/DiffEqOperators.jl/commit/1d6deace947aa10b8271ecc6b0ba71b2e440da3c
