### ISSUE TITLE
time dependend BC

### ISSUE THREAD

**Issue by scheidan** [JuliaDiffEq/DiffEqOperators.jl#220]
Thanks for this useful package!

I was wondering how to implement best time-depended BC. Is this the recommended approach?
```Julia
function heat(u,p,t)
    bc = DirichletBC(cos(t*1.5), sin(t))
    Δ*bc*u
end
```
(modified from `example/heat_equation.jl`)

**Comment by ChrisRackauckas** [comment]
Yeah, that's a good way to do it. The types are all lazy, so creating them each time is essentially free and you should feel safe doing so.

**Comment by rveltz** [comment]
what do you mean by lazy?

**Comment by ChrisRackauckas** [comment]
It's just type information and nothing is actually constructed until you concretize. And then the matmuls just call a generated kernel.
