### ISSUE TITLE
Concretization struggles using CenteredDifference with nonuniform discretization spacing 

### ISSUE THREAD

**Issue by cristophermoen** [JuliaDiffEq/DiffEqOperators.jl#226]
The concretization of the `DerivativeOperator` from the `CenteredDifference` function, i.e.,  `Array(CenteredDifference(derivative_order::Int,   approximation_order::Int, dx, len::Int))` does not seem to be working correctly when `dx` is an array describing a nonuniform discretization.

**Comment by ChrisRackauckas** [comment]
Fixed!
