### ISSUE TITLE
DiffEqOperator Interface Compatibility

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DiffEqOperators.jl#24]
It'll be important to match the interface for it all to work in the stiff solvers "automatically". Here's a few points:

The problem is with `update_coefficients!(A,t,u)` which is different here. 

https://github.com/JuliaDiffEq/DiffEqBase.jl/blob/master/src/diffeq_operator.jl#L6

The ODE solver needs to be able to call that an have the ODE update its coefficients. But also

https://github.com/JuliaDiffEq/PDEOperators.jl/blob/8ddcb5368824919ed46608f4ad2117b268e78b25/src/linear_operator.jl#L399

the call doesn't update the coefficients. I think that somehow there needs to be a system for `if <: Number` then BC is constant, otherwise assume the user gives a function `a = bc(t)` where `a` is the value for the constant you want.

**Comment by shivin9** [comment]
Yeah that was the system before, I was using anonymous functions with constant BC being represented as  
`t->constant`. But then we decided that we should let the user update the values as he might do so in all sorts or different ways.

**Comment by ChrisRackauckas** [comment]
I think I made a big mistake when I suggested that be changed. That's my bad.
