### ISSUE TITLE
Broken full tests vs Strang

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DiffEqOperators.jl#35]
https://github.com/JuliaDiffEq/DiffEqOperators.jl/blob/master/test/derivative_operators_interface.jl#L12

**Comment by shivin9** [comment]
https://github.com/JuliaDiffEq/DiffEqOperators.jl/commit/2b9e0d9dc14f845fcf90c0bb8dbff0270d63f02a

**Comment by ChrisRackauckas** [comment]
The issue is described by:

```julia
full(A, 10)

10×10 Array{Float64,2}:
 0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  0.0
 0.0  -2.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0  0.0
 0.0   1.0  -2.0   1.0   0.0   0.0   0.0   0.0   0.0  0.0
 0.0   0.0   1.0  -2.0   1.0   0.0   0.0   0.0   0.0  0.0
 0.0   0.0   0.0   1.0  -2.0   1.0   0.0   0.0   0.0  0.0
 0.0   0.0   0.0   0.0   1.0  -2.0   1.0   0.0   0.0  0.0
 0.0   0.0   0.0   0.0   0.0   1.0  -2.0   1.0   0.0  0.0
 0.0   0.0   0.0   0.0   0.0   0.0   1.0  -2.0   1.0  0.0
 0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0  -2.0  0.0
 0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0  0.0
```

see that it has zeros on the ends. I think one way to solve this would be by simply returning the stencil, since in general incorporating the BCs would not always be possible.

**Comment by shivin9** [comment]
well this particular case can be solved, the thing is that I am manually setting the boundaries to `0` in Dirichlet0 BC which is correct but not when making the `full` matrix of the operator
