### ISSUE TITLE
problems adding package

### ISSUE THREAD

**Issue by francispoulin** [JuliaDiffEq/DiffEqOperators.jl#38]
I am keen to play with this package and tried adding it using the standard approach but I get an error.

Can someone point out what might have gone wrong?

```

julia> Pkg.add("DiffEqOperators")
ERROR: unknown package DiffEqOperators
macro expansion at ./pkg/entry.jl:53 [inlined]
(::Base.Pkg.Entry.##1#3{String,Base.Pkg.Types.VersionSet})() at ./task.jl:335
Stacktrace:
 [1] sync_end() at ./task.jl:287
 [2] macro expansion at ./task.jl:303 [inlined]
 [3] add(::String, ::Base.Pkg.Types.VersionSet) at ./pkg/entry.jl:51
 [4] (::Base.Pkg.Dir.##4#7{Array{Any,1},Base.Pkg.Entry.#add,Tuple{String}})() at ./pkg/dir.jl:36
 [5] cd(::Base.Pkg.Dir.##4#7{Array{Any,1},Base.Pkg.Entry.#add,Tuple{String}}, ::String) at ./file.jl:70
 [6] #cd#1(::Array{Any,1}, ::Function, ::Function, ::String, ::Vararg{String,N} where N) at ./pkg/dir.jl:36
 [7] add(::String) at ./pkg/pkg.jl:117

```

**Comment by shivin9** [comment]
well I think it's not registered with `Metadata` yet. You can clone it directly though and it should work then.

**Comment by ChrisRackauckas** [comment]
There was a release: https://github.com/JuliaDiffEq/DiffEqOperators.jl/releases , but attobot wasn't enabled. Let me get that fixed up.

**Comment by ChrisRackauckas** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/11523

**Comment by francispoulin** [comment]
Thank you both.  I have yet to clone a package and tried this, but it clearly didn't work.

Pkg.clone("https://github.com/JuliaDiffEq/DiffEqOperators.jl.git")

What is the proper syntax to clone this package?

**Comment by francispoulin** [comment]
I stand corrected.  I think the following worked.  I will try and remember this for next time.

julia> Pkg.clone("https://github.com/JuliaDiffEq/DiffEqOperators.jl.git")
INFO: Cloning DiffEqOperators from https://github.com/JuliaDiffEq/DiffEqOperators.jl.git
INFO: Computing changes...
INFO: No packages to install, update or remove

**Comment by ChrisRackauckas** [comment]
It's registered now.

**Comment by francispoulin** [comment]
Thank you.  One last question. If I have a cloned copy how should I remove it if I wanted to get the registered copy?

**Comment by ChrisRackauckas** [comment]
Usually you go back to the last release with `Pkg.free("DiffEqOperators")`. However, if cloned I'm not sure if that'll do it, so you may have to `Pkg.rm("DiffEqOperators"); Pkg.add("DiffEqOperators")`.

**Comment by francispoulin** [comment]
Thanks.  I did "rm", "update" and then "add" and that seems to work nicely.  I will remember this for next time.
