### ISSUE TITLE
Simple example of discretizing a univariate diffusion with reflecting boundaries

### ISSUE THREAD

**Issue by jlperla** [JuliaDiffEq/DiffEqOperators.jl#44]
@FernandoKuwer  As a first test of discretizing an operator to solve a HJBE:
- Take a look at https://github.com/econtoolkit/continuous_time_methods/blob/master/operator_discretization_finite_differences.pdf  equation (3), (4), and (7) to (12).
- What we want to do is first recreate this example with the following simplifications to start with a uniform grid and reflecting boundaries at both corners
- We should then add a simple solution to a trivial HJBE as a test.  See (54) to (56) in those notes.
   - For the most part, I think that solving a simple HJBE for a fixed discount rate should be generic given a discretized operator (though you can do these operations directly in a test for now).
   - You can see the matlab implementation of these in https://github.com/econtoolkit/continuous_time_methods/blob/master/matlab/tests/discretize_univariate_diffusion_test.m along with a simple https://github.com/econtoolkit/continuous_time_methods/blob/master/matlab/lib/discretize_univariate_diffusion.m for an implementation.  We want to make sure that we verify these are correct as we go through.

You can discuss the plan's with Chris about the steps to accomplish this (as upwinding is incomplete in the library), but one idea is to start with the no drift example (which doesn't require upwind) then start adding tests.  Eventually, we will want to support having absorbing barriers rather than only reflecting barriers, but this is a good place to start.

**Comment by ChrisRackauckas** [comment]
Here's a video that explains the steps to get there, and how to connect the operators to those MATLAB implementations, and what concrete steps need to be taken.

https://www.youtube.com/watch?v=a3Bz4Whe0SE

**Comment by jlperla** [comment]
Closing this as it is superceded by #46 and #48
