### ISSUE TITLE
Document the new discretization and boundary values

### ISSUE THREAD

**Issue by jlperla** [JuliaDiffEq/DiffEqOperators.jl#51]
@stevenzhangdx  @FernandoKuwer 
I added in a placeholder `.tex` file in `/docs/linear_operators_overview.tex` which you can compile.  The idea is that you can write up all of the algebra required to understand the discretization of the operators and boundary values.  Remember that the main description is the https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues/260 issue.  In particular, figuring out the B, Q, R, A, etc. matrices.

Instead of worrying about the solutions to the full PDEs, we should start by just looking at the stationary problems.  The PDEs can come later once we figure out how the discretization works.  

I also put the julia code for at least one or two of them in the `/docs/operator_examples` directory.  We should put all of the code there that implements our descriptions.

**Comment by jlperla** [comment]
Guys https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues/260#issuecomment-370111767

Chris has done most of the work for you. So writing this up cleanly and checking that this makes sense is the goal. Don't worry about writing up the connection to the spectral and finite element methods.

**Comment by FernandoKuwer** [comment]
@stevenzhangdx I have merged our comments on the two expressions that we both do not fully understand (and your original text is still in the file, just in case you don’t like the merged version. It is on the top of the merged comment but between \iffalse \fi opperators in order to not show up).

**Comment by jlperla** [comment]
Some comments from editing the document:
- Need a notation for the extension of the domain and the domain itself.  This will become especailly important with jumps
  - Use $i=1,... I$ as the grid in the interior.  So the solution to the discretized function is $u \in R^I$ if stationary
  - The total size if $\hat{I} > I$.
  - In general, use a hat when looking at the extension.  Then $\hat{u} \in R^{\hat{I}}$ is the extension of $u \in R^I$.  Replace the current $v$ with $\hat{u}$
  - For the steady state, just drop the $t$ for now.
  - When dealing with a univariate function with 2 sides, can denote the extra points as $I_L$ and $I_H$ so that $\hat{I} = I + I_L + I_H$.  For example, with a univariate diffusion operator, $I_L = I_H = 1$
  - $R$ is a $I \times \hat{I}$ matrix, etc.
  - Change the basic notation to stack the BC1 and BC2 on the bottom instead of on the top and bottom.
  - Rename BC1 and BC2.   
- When we start writing up the examples, we can make the main description more generic
  -  As we go through the first example, we can convert the main description to be fully generic in terms of $\hat{I}, I,$ etc.
  - Move the Dirichlet, etc. to the examples sections to map into the B, Q, etc.
  - I think (6) and (7) will be clearer with the generic notation.
  - Try to get rid of the $v_t$, etc. notation for the discretization?.  Too easy to confuse with a partial...  Can abuse the $u$ vector and the $u$ function notation?
  - Lets get rid of the $f$ and just use $u$...

**Comment by jlperla** [comment]
Steps:
- [ ] Go through the current description and update the obvious notation from above, be very clear on the sizes of all vectors/matrices
- [ ] Start with the examples 3.1, 3.2, etc. and write down the $B$, $R$, etc. and move anything not generic out of the main description.
