### ISSUE TITLE
L*u mutates u if L has Dirichlet1 boundary condition

### ISSUE THREAD

**Issue by MSeeker1340** [JuliaDiffEq/DiffEqOperators.jl#52]
```julia
using DiffEqOperators
using DiffEqOperators: convolve_BC_left!, convolve_BC_right!
N = 10
u = ones(N)
utmp = zeros(10)
lb = 2.2; rb = 3.3
L = DerivativeOperator{Float64}(2,2,1.9,N,:Dirichlet,:Dirichlet,BC=(lb,rb))

@show u
A_mul_B!(utmp, L, u)
@show u
u = ones(N)
convolve_BC_left!(utmp, u, L)
@show u
u = ones(N)
convolve_BC_right!(utmp, u, L)
@show u

u = [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
u = [2.2, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 3.3]
u = [2.2, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
u = [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 3.3]
```

This is not an issue if we enforce `u` to satisfy the boundary condition. Nevertheless `L * u` having a mutating effect on `u` is probably not good, especially when `L` is used in a differential equation solver.

Using the convention proposed in #42 should make this a non-issue.

**Comment by ChrisRackauckas** [comment]
We instead want to change the whole implementation of the boundaries. See https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues/260#issuecomment-370111767 .
