### ISSUE TITLE
BC Overhaul

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DiffEqOperators.jl#53]
Long discussions with @dlfivefifty and @jlperla led to a big shift in the way we are doing BCs. The idea is outlined https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues/260#issuecomment-370111767 . For DiffEqOperators.jl to change to support this, we need to do the following:

1. The DerivativeOperators should be the non-square `A` interior stencil calculations. All interior, no boundaries. `full`, `sparse`, `banded`, etc. should be defined on the stencil to make it easy to get matrices out.
2. Lazy `R` should be created. That's super simple of course. And full/space/etc. here too.
3. Lazy `Q` should be created for each of the FDM boundary types. So there should be a constructor `FDMExtension(...)` which takes in boundary types and spits out an operator which does this operation. `Q` can be an affine operator. We'll need to define that such that `(Qa,Qb) = full(Q)`. And full/space/etc. here too.
4. In this form, `v_t = L*v` can be written at `v_t = A*Qa*v + A*Qb`.
5. We should have a lazy `L`, dependent on the BCs, which is `L*v = A*Qa*v + A*Qb`. 
6. In this form, `(L1+L2)*v` is well-defined as `(A1+A2)*Qa*v + (A1+A2)*Qb`.
7. We should rename `DerivativeOperator` to `FDMDerivativeOperator` and then `FiniteDifference` to `FDMIrregularDerivativeOperator` (or something like that). Both `<: AbstractDerivativeOperator`. 

Every step of the way should get tests of course.

**Comment by jlperla** [comment]
@stevenzhangdx @FernandoKuwer   Note, even more description for your writeup and test cases.
