### ISSUE TITLE
BC when stencil reaches out of grid

### ISSUE THREAD

**Issue by fgerick** [JuliaDiffEq/DiffEqOperators.jl#58]
Probably somewhere this has already been discussed!? When the stencil length is larger than 3 the stencil coefficients of the boundaries, except for the ``None`` boundary condition, are not calculated correctly. I understand the way BC are imposed is being overhauled, but this seems to me to be decoupled from this issue? When constructing the linear operator, in the new or the old way, the boundary coefficients need to be calculated in the same manner. Please tell me, if I'm missing something. I'd be happy to help implementing the boundary conditions correctly, i.e. taking the stencil length into account and calculating left and right handed coefficients for the "out of boundary" points.

**Comment by ChrisRackauckas** [comment]
Yeah this is slightly decoupled from the BC overhaul. What should be happening is the uncentered discretization should be used. For example, a 4th order discretization of the 2nd derivative one away from the boundary should use the stencil that is 2 to the left and 1 to the right. So basically you need to adapt which derivative you're using near the boundary to make sure it only ever goes to the boundary point. I don't believe we are properly doing all of this though.

**Comment by fgerick** [comment]
Okay, yes. I didn't really read into the BC overhaul. Do you think if I put some work into this now it is easily adaptable to the new way of putting together the linear operators?

**Comment by ChrisRackauckas** [comment]
Yes, getting this done would be very helpful. Basically what we to start BC overhaul is to just get very solid the "BC-less" operators, i.e. an operator whose stencil is correct (i.e. does this de-centering).

**Comment by fgerick** [comment]
As I understand, the stencils of the ``Dirichlet`` boundary condition should essentially equal to those of the ``None`` condition? Except for the first column, that can be set to 0.

**Comment by ChrisRackauckas** [comment]
No, the stencils and the BCs should be kept separate.

**Comment by fgerick** [comment]
I see, you mean the stencils influenced by the boundary are computed and stored anyways and the BC is applied ontop.

**Comment by ChrisRackauckas** [comment]
The stencil is always a mapping from the full domain to the interior. The mapping from the interior to the full domain is what holds the BCs.
