### ISSUE TITLE
Integrating StaticArrays(Documentation)

### ISSUE THREAD

**Issue by shivin9** [JuliaDiffEq/DiffEqOperators.jl#6]
We decided to implement  `stencil_coefs` of the PDEOperator as a StaticVector as they are stored on stack rather than on the heap and are hence fast.

But for optimum performance they need to be initialized with both `Type` and `Length` like `SVector{Length, Type}` which made the constructor for LinearOperator look ugly. `A = LinearOperator{Float64, SVector{1000, Float64}}` for an operator working on 1000 dimensional vectors.

So we fixed it by creating an internal constructor
``` julia
    (::Type{LinearOperator{T}}){T<:Real}(dorder::Int, aorder::Int, dim::Int) =
    LinearOperator{T, SVector{dorder+aorder-1,T}}(dorder, aorder, dim)
```
which decides the length of the SVector at runtime using the given input parameters.

**Comment by ChrisRackauckas** [comment]
>which decides the length of the SVector at runtime using the given input parameters.

It's not necessarily runtime because of https://github.com/shivin9/PDEOperators.jl/pull/5. Hyperpurity makes this inferrable, and so it's quasi-compile-time. Hard to explain, but check it.
