### ISSUE TITLE
Taking 2D operators seriously

### ISSUE THREAD

**Issue by clason** [JuliaDiffEq/DiffEqOperators.jl#73]
*First, I apologize for the presumptuous title; I couldn't think of a better one since the question is a bit broad. Please feel free to edit it to something more appropriate.*

For prototyping algorithms for PDE-constrained optimization, I frequently need a simple discretization of two-dimensional elliptic partial differential operators on a uniform structured grid, for which `FEniCS` is overkill. (To demonstrate how simple: in Matlab I often just use `A = gallery("poisson",N)`...) 

I am aware that I can apply such an operator via the tensor trick `Au = D1*u + u*D1` and use  `IterativeSolvers` to solve the corresponding PDEs, but for various reasons (avoiding unnecessary inexactness in linear solves, precomputing factorizations for performance, including in block operators for one-shot or Newton-type methods for solving optimality systems), I need an actual matrix representation for `A` (ideally, in either a sparse or banded form). 

Is there any way to obtain such a matrix from `DiffEqOperators`? Are there any (plans for)  convenience constructors?

**Comment by ChrisRackauckas** [comment]
Yes, we plan to have a lazy Kron so that way you can build the block-banded matrix, but it will take some work and I wouldn't expect it too soon.

**Comment by clason** [comment]
That is good to know (and no hurry)! In the meantime, is there some other way I can construct such a matrix (it doesn't have to be really efficient since I'm only doing it once as a setup.)

**Comment by ChrisRackauckas** [comment]
`AbstractMatrix(A)`, `Matrix(A)`, etc. We need to update the docs as well. Give us a a month or so to put this into shape.

**Comment by clason** [comment]
That's fair; I was in fact worried that this was a bad time for a feature (or documentation) request. But just to make sure: This *should* be possible right now by manually forming the Kronecker product? Because neither `Matrix(D1)` nor `AbstractMatrix(D1)` (nor `kron(D1,Id)` for a manually constructed identity matrix) works for me...

**Comment by ChrisRackauckas** [comment]
I thought we made those for the structured full matrices already, but we may still need to upgrade from using `full` (just got back from Juliacon so I need to check where we're at in more detail). Once the full/banded/etc matrix is made `kron` should just be the normal kron. And I wonder if there's a special `kron` for BlockBandedMatrices.

**Comment by clason** [comment]
Ah, got it: It's not `Matrix(D1)`, it's now `convert(Array,D1)`. Then the following works:
```julia
using LinearAlgebra, SparseArrays, DiffEqOperators
N = 10
h = 1/N
D1 = convert(Array,DerivativeOperator{Float64}(2,2,h,N,:Dirichlet,:Dirichlet))
D1 = convert(SparseMatrixCSC,D1)
Id = Matrix(I,N,N)
A = kron(D1,Id) + kron(Id,D1)
```
I'll try to find a way without the intermediate full array, but since this is 1D, it shouldn't be too bad.
