### ISSUE TITLE
Package DiffEqOperators does not have LinearAlgebra in its dependencies

### ISSUE THREAD

**Issue by Octogonapus** [JuliaDiffEq/DiffEqOperators.jl#78]
I am trying to run the quick start notebook for https://github.com/JuliaRobotics/RigidBodySim.jl and I am running into an issue when I try to run `using RigidBodySim`.

This error prints out repeatedly (indefinitely as far as I can tell):
```
┌ Warning: Package DiffEqOperators does not have LinearAlgebra in its dependencies:
│ - If you have DiffEqOperators checked out for development and have
│   added LinearAlgebra as a dependency but haven't updated your primary
│   environment's manifest file, try `Pkg.resolve()`.
│ - Otherwise you may need to report an issue with DiffEqOperators
└ Loading LinearAlgebra into DiffEqOperators from project dependency, future warnings for DiffEqOperators are suppressed.
┌ Warning: The call to compilecache failed to create a usable precompiled cache file for OrdinaryDiffEq [1dea7af3-3e70-54e6-95c3-0bf5283fa5ed]
│   exception = Required dependency DiffEqOperators [9fdde737-9c7f-55bf-ade8-46b3f136cc48] failed to load from a cache file.
└ @ Base loading.jl:963
```

I am opening an issue here as it seems like that's what Julia is telling me to do. Sorry if this is isn't the right place, I am very new to Julia.

**Comment by ChrisRackauckas** [comment]
You just need to do `]resolve`. LinearAlgebra is a standard library package that comes with Julia. It seems like your local environment just needs to re-resolve to fix itself.

**Comment by Octogonapus** [comment]
Doing `]resolve` prints this and does not change the warning:
```
 Resolving package versions...
  Updating `~/.julia/environments/v1.0/Project.toml`
 [no changes]
  Updating `~/.julia/environments/v1.0/Manifest.toml`
 [no changes]
```

**Comment by jlperla** [comment]
I had similar issues today. I still do not have a working setup

**Comment by ChrisRackauckas** [comment]
It looks like the package repository got a little messed up and isn't dealing with dependencies right. This is an upstream issue that should get fixed shortly. The commit in question is:

JuliaRegistries/General@c6032b2#diff-60ad0b44e938d9b35732a3e174a29627

It's not a DiffEqOperators issue but more generally a Julia-wide package ecosystem issue.

**Comment by mauro3** [comment]
I still get this warning with the linked commit in my .julia/registries/General.

**Comment by jlperla** [comment]
I just did a `] up; resolve; precompile` and am not up and running without any problems.

**Comment by ChrisRackauckas** [comment]
I'm not getting problems today either, so it sounds like it was solved overnight.

**Comment by mauro3** [comment]
Yep, works now.
