### ISSUE TITLE
full() replacement for Julia 1.0

### ISSUE THREAD

**Issue by mitkoge** [JuliaDiffEq/DiffEqOperators.jl#83]
Please excuse my entry level this might be more question than issue. 

I tried to use DiffEqOperators on Julia 1.0 as follows

using DiffEqOperators
xs= collect(0 : 1/9 : 1)
D1b = DerivativeOperator{Float64}(1,2,xs[2],length(xs),:None,:None)

so far ok but when i try to inspect using full(D1b ) i get "full not defined". 
I guess Base.full is kind of depreciated for Julia 1.0.

Trying Matrix(D1b) gives "MethodError: Cannot `convert` an object of type DerivativeOperator{Float64,StaticArrays.SArray{Tuple{3},Float64,1,3},:None,:None} to an object of type AbstractArray{T,2} ..."

What is the preferred method to get non lazy matrix from DerivativeOperator? Collect()?
Or just stick with Julia 0.6 for a while?

**Comment by ChrisRackauckas** [comment]
The full method was kind of broken for a few boundary conditions. We need some work to correctly replace it

**Comment by ChrisRackauckas** [comment]
Or we should just return the stencil matrix
