### ISSUE TITLE
Gradient on a 2D mesh for a vector field

### ISSUE THREAD

**Issue by mleprovost** [JuliaDiffEq/DiffEqOperators.jl#84]
Hello,

I would like to solve an advection problem on a 2D mesh for a 2D vector field( velocity field U with two components Ux(x,y,t) and Uy(x,y,t))
![codecogseqn 6](https://user-images.githubusercontent.com/38221506/48655860-f2752400-e9d1-11e8-918f-d4a2ea5d578c.gif)
So the array for my velocity will be 2xNxN  if the spatial grid is N x N,
 and its gradient will be 2x2xNxN
(after that, the PDE will be  semi-discretized and integrated with an ODE solver)

I don't know how to use the function DerivativeOperator{Float64}(2,1,h,N,:Dirichlet0,:Dirichlet0), nor how to reshape my data to compute \nabla U on this space domain, all the examples I saw are for 1D functions on a 2D mesh

Thank you for  having created these amazing packages !

**Comment by ChrisRackauckas** [comment]
To solve this using this package I think you'd need lazy kron which we don't have yet or some reshape trickery.
