### ISSUE TITLE
Lazy composed PDE Operators

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DiffEqOperators.jl#9]
A nice feature would be able to compose these lazy operators. This will be difficult though. It would be killer to be able to support intermediates of scalars, functions, and `AbstractArray`s so that way something like

```julia
u_t = a(t,x)u_xx + b(t,x)u_x
```

will compose to a single operator on the LHS, or

```julia
u_t = (D*u_x)_x
```

where `D` is some vector of diffusion constants. 

The composition should include the ability to combine with `I`, so that way `I - gamma*L` works. 

Of course, we'd have to start with a simpler version, but this kind of composition would be absolutely awesome for using stiff integrators.

**Comment by shivin9** [comment]
Do you mean that the elements of the Transformation map will become functions now (say 2+x+sin(x))?

**Comment by ChrisRackauckas** [comment]
They probably shouldn't output the function, but instead should evaluate all of the proper functions so that way it outputs the solution.

If you have a design go ahead an implement, though I'm not entirely sure what the correct design for this is right now anyways.
