### ISSUE TITLE
Maxwell Stefan Equation

### ISSUE THREAD

**Issue by MaxwellStefan** [JuliaDiffEq/DiffEqOperators.jl#91]
Dear All,

i am a phd student who is currently working on the Stefan-Maxwell equation to describe a diffusion problem. Similarly to the "Standard"Diffusion Equation, setting up a mass balance results in a second order PDE. To show the equations,  I provided some files... 
Opposed to the "Standard" Diffusion equation, one does not simply combine the two Equations (1st Stefan Maxwell 2nd Mass Balance) of the PDE-system in one Equation. Here the concentrations of each components are densities \rho. In the chair im working, we are able to use nonlinear models to describe the chemical potential \mu e.g as a function of \rho, thus the notation f(\rho). 
I am fascinated by the simplicity of rewriting a PDE in the way it is presented in DiffEqOperators.jl. My idea to tackle this problem using the operators was to classify the given boundaries and translate them to variable \rho (using the physical/algebraic relationships governing the system). From a physical standpoint these translations also make sense.  So to my question, is it valid to utilize the operaters in such a way? And if not what would be name of such a system (coupled PDEs?) and how would you solve it? Thanks for your help...

a nice day wishes,
Dominik

![Github1](https://user-images.githubusercontent.com/50300257/57199263-58079d80-6f7d-11e9-9b55-3a99bd483d27.PNG)
![Github2](https://user-images.githubusercontent.com/50300257/57199265-5ccc5180-6f7d-11e9-93cf-d61b47e38029.PNG)

**Comment by ChrisRackauckas** [comment]
Yes, if I'm reading it correctly then that's a valid way to use the operators, though I would wait since we are reforming the BC implementation.

**Comment by MaxwellStefan** [comment]
Hey Chris,

thanks for your assessment to my problem. I started the implementation using the operators and i will compare it to my work in python. Keep on the good work.

a successfull week wishes,

Dominik
