### ISSUE TITLE
Boundary condition redo

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DiffEqOperators.jl#98]
Here's a brief overview: [ghost_node.pdf](https://github.com/JuliaDiffEq/DiffEqOperators.jl/files/3267835/ghost_node.pdf). Ask if you have any questions on the details. So here's what we need to do in order to get there.

- [x] Change DerivativeOperator to be an implementation of `L`. Its `mul!` method is just the application of the stencil. The key is that this `mul!` does need to care about how the `u[1]` or `u[end]` values came to be: it just is an application of the stencil on the whole `u` to something of size 2 less than `u`. 
- [x] Make sure the DerivativeOperator handles stencils of size larger than 1. It should take care to not use values over the boundary though by changing the discretization point. If `m` is the center of the stencil, as a large stencil approaches the boundary it should do [x,x,x,m,x,x,b] then [x,x,x,x,m,x,b] then [x,x,x,x,x,m,b]. Notice that it never centers at the boundary though, since it's N x (N+2).
- [x] Create `RobinBC` which is a padding operator from N -> Nx2 arrays. Here's a quick Dirichlet version: https://gist.github.com/ChrisRackauckas/54aa5298ec173652455221ccbacbfb6a . 
- [x] Make dispatches that optimize DerivativeOperator for BoundaryPaddedArray. Basically, just pass the `u` part to the interior convolution, and specialize the boundary handling code to use the `.l` and `.r` directly instead of full indexing.

When that's done, the lazy part of the operator is complete! Now for the concretization:

- [x] RobinBC should have a concretization to a tuple `(Q_L,Q_b)` for the linear and bias part (since in general it's affine). The concretization functions to implement are `Array`, `SparseMatrixCSC`, and `BandedMatrix`.
- [x] Concretization of `DerivativeOperator` to `N x (N+2)`. Just the derivative stencil. Needs to make sure the boundary does the right re-centering as it approaches the boundary.
- [x] Test cases to make sure the concretization looks like one would expect.
- [x] Test cases to make sure concretizations and operators act the same as lazy versions.

**Comment by xtalax** [comment]
I'm going to have a crack at this, starting with the RobinBC padding operator. 

To get the Derivative Operator to handle large stencils at the boundary as you suggest, there will be need for code that can correctly generate lopsided stencils of arbitrary order and arbitrary offset. I have some `SymPy.jl` code that can generate stencils of arbitrary order by expanding a Taylor series about the boundary, but am unsure of how to generalize this to an arbitrary offset, or if there is a better way to do this than by using SymPy. I'll have a think about this.

For multidimensional `u`, as in a PDE, lopsided stencils in one dimension start to break as the offset increases. They only remain valid for planar fourier components of `u` incident to the boundary along the dimension that the stencil is convolved along. So later some code will be needed that can generate multidimensional stencils of arbitrary order and with an arbitrary offset in an arbitrary number of dimensions, including offsets that fall outside of the stencil size to deal with the boundary conditions, which is hurting my head a bit.

Feedback greatly appreciated, watch this space for updates as to how far I get

**Comment by ChrisRackauckas** [comment]
@xtalax this is already going on with the following PRs:

https://github.com/JuliaDiffEq/DiffEqOperators.jl/pull/103
https://github.com/JuliaDiffEq/DiffEqOperators.jl/pull/106
https://github.com/JuliaDiffEq/DiffEqOperators.jl/pull/102
https://github.com/JuliaDiffEq/DiffEqOperators.jl/pull/100

>To get the Derivative Operator to handle large stencils at the boundary as you suggest, there will be need for code that can correctly generate lopsided stencils of arbitrary order and arbitrary offset. I have some SymPy.jl code that can generate stencils of arbitrary order by expanding a Taylor series about the boundary, but am unsure of how to generalize this to an arbitrary offset, or if there is a better way to do this than by using SymPy. I'll have a think about this.

This is done by the Fornberg method more directly, and the PR with the fix is https://github.com/JuliaDiffEq/DiffEqOperators.jl/pull/106 . 

This is highly active right now since we have two summer students, @shivin9 and @ajozefiak working on this. That said, there is still a lot to be done, including adding good tests for the higher order stencils which utilize this extra boundary handling. If you can work out some tests so we can double check we're doing it all good, that would be a great PR. If you want to join our development discussions, they are happening in the Julia Slack (https://slackinvite.julialang.org/) in the #diffeq-bridged channel, or you can get there through the JuliaDiffEq Gitter (https://gitter.im/JuliaDiffEq/Lobby). Since there are student components going on here I would like to make sure the work doesn't overlap, but there are still very many things to do, such as working out high order unit tests and making the operators work with non-uniform grid spacing (i.e. updating FiniteDifference to this new form, but through type information. We can discuss this more)

**Comment by xtalax** [comment]
Great to see things progressing so quickly, I'll have a look at writing some tests for the boundary handling then.

**Comment by ChrisRackauckas** [comment]
Just analytical tests and right boundary indexing are left.
